package com.spartan.attendance.entity;

public enum AuditAction {
    LOGIN, LOGIN_FAILED, LOGOUT,
    CHECK_IN, CHECK_OUT, ATTENDANCE_CORRECTION,
    USER_CREATE, USER_UPDATE, USER_STATUS_CHANGE, USER_DELETE, PASSWORD_RESET, PASSWORD_CHANGE,
    WORK_LOCATION_CREATE, WORK_LOCATION_UPDATE, WORK_LOCATION_STATUS_CHANGE,
    SHOP_CREATE, SHOP_UPDATE, SHOP_STATUS_CHANGE, SHOP_DELETE
}
