package com.spartan.attendance.dto;

import com.spartan.attendance.entity.Status;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/** Admin-side create / edit of a shop. A blank code is generated by the server; a missing radius uses the default. */
public record ShopRequest(
        @Size(max = 32) @Pattern(regexp = "^[A-Za-z0-9_-]*$", message = "Shop code can only contain letters, digits, - and _") String code,
        @NotBlank(message = "Shop name is required") @Size(max = 150) String name,
        @Size(max = 120) String locality,
        @Size(max = 80) String region,
        @Size(max = 255) String address,
        @Pattern(regexp = "^$|^[0-9+() -]{7,20}$", message = "Phone number looks wrong") String phone,
        @NotNull(message = "latitude is required") @DecimalMin("-90.0") @DecimalMax("90.0") Double latitude,
        @NotNull(message = "longitude is required") @DecimalMin("-180.0") @DecimalMax("180.0") Double longitude,
        @Min(value = 10, message = "Radius must be at least 10 m") @Max(value = 500, message = "Radius cannot exceed 500 m") Integer allowedRadiusMeters,
        Long assignedOfficerId,
        Status status) {
}
